### ISSUE TITLE
How to remove list-item chevron  icon

### ISSUE THREAD

**Issue by raindy29** [nolimits4web/Framework7-Vue#208]
I hope that the (>)icon will not show

            </f7-list-item>
              <f7-list-item link="/product" title="test" link-view="#main-view" 
              link-close-panel
              >
           </f7-list-item>

**Comment by araimbekoff** [comment]
Try it:
:link="(your_condition)?'#main-view': null"

**Comment by nolimits4web** [comment]
Using CSS:
```css
.list-block .item-link .item-inner {
  background:none;
}
```
